/**
 * Created by Ilya on 09.01.2017.
 */
export const GET_ADVERTS_REQUEST = 'GET_ADVERTS_REQUEST';
export const GET_ADVERTS_SUCCESS = 'GET_ADVERTS_SUCCESS';
export const GET_ADVERTS_FAIL = 'GET_ADVERTS_FAIL';
export const ADD_ADVERT_REQUEST = 'ADD_ADVERT_REQUEST';
export const ADD_ADVERT_SUCCESS = 'ADD_ADVERT_SUCCESS';
export const ADD_ADVERT_FAIL = 'ADD_ADVERT_FAIL';
export const DELETE_ADVERT_REQUEST = 'DELETE_ADVERT_REQUEST';
export const DELETE_ADVERT_SUCCESS = 'DELETE_ADVERT_SUCCESS';
export const DELETE_ADVERT_FAIL = 'DELETE_ADVERT_FAIL';
export const DELETE_ADVERT_RESET = 'DELETE_ADVERT_RESET';
export const UPDATE_ADVERT_REQUEST = 'UPDATE_ADVERT_REQUEST';
export const UPDATE_ADVERT_SUCCESS = 'UPDATE_ADVERT_SUCCESS';
export const UPDATE_ADVERT_FAIL = 'UPDATE_ADVERT_FAIL';
export const SHOW_DELETE_CONFIRMATION = 'SHOW_DELETE_CONFIRMATION';
export const CLOSE_DELETE_CONFIRMATION = 'CLOSE_DELETE_CONFIRMATION';
export const GET_ADVERT_DETAILS_REQUEST = 'GET_ADVERT_DETAILS_REQUEST';
export const GET_ADVERT_DETAILS_SUCCESS = 'GET_ADVERT_DETAILS_SUCCESS';
export const GET_ADVERT_DETAILS_FAIL = 'GET_ADVERT_DETAILS_FAIL';