/**
 * Created by Ilya on 09.01.2017.
 */
export const GET_ADVERTS_REQUEST = 'GET_ADVERTS_REQUEST';
export const GET_ADVERTS_SUCCESS = 'GET_ADVERTS_SUCCESS';
export const GET_ADVERTS_FAIL = 'GET_ADVERTS_FAIL';
export const ADD_ADVERTS_REQUEST = 'ADD_ADVERTS_REQUEST';
export const ADD_ADVERTS_SUCCESS = 'ADD_ADVERTS_SUCCESS';
export const ADD_ADVERTS_FAIL = 'ADD_ADVERTS_FAIL';
export const DELETE_ADVERT_REQUEST = 'DELETE_ADVERT_REQUEST';
export const DELETE_ADVERT_SUCCESS = 'DELETE_ADVERT_SUCCESS';
export const DELETE_ADVERT_FAIL = 'DELETE_ADVERT_FAIL';
export const DELETE_ADVERT_RESET = 'DELETE_ADVERT_RESET';