/**
 * Created by Ilya on 05.08.2017.
 */
export const SET_FILTER_CLOSED = 'SET_FILTER_CLOSED';
export const SET_FILTER_DATE = 'SET_FILTER_DATE';
export const FILTERING_DATE_ALL = 'FILTERING_DATE_ALL';
export const FILTERING_DATE_WEEK = 'FILTERING_DATE_WEEK';
export const FILTERING_DATE_MONTH = 'FILTERING_DATE_MONTH';
export const FILTERING_DATE_YEAR = 'FILTERING_DATE_YEAR';